# Compose file origin: https://gitlab.com/tango-controls/docker/tango-cs
# Changes to support podman and podman-compose
# The following error in /tmp/tango-* appears when running this compose file using podman-compose:
#   Tango exception
#   Severity = ERROR
#   Error reason = BAD_PARAM
#   Desc : This server must run on 615f459adb4f and not on localhost
#   Origin : Starter::check_host()
# This must be related to podman's networking and changing the container's hostname to localhost is a workaround

version: '3.7'
services:
  mysql:
    image: registry.gitlab.com/tango-controls/docker/mysql:5
    environment:
     - MYSQL_ROOT_PASSWORD=root

  tango-cs:
    hostname: localhost
    image: registry.gitlab.com/tango-controls/docker/tango-cs:9
    ports:
     - "10000:10000"
    environment:
     - TANGO_HOST=localhost:10000
     - MYSQL_HOST=mysql:3306
     - MYSQL_USER=tango
     - MYSQL_PASSWORD=tango
     - MYSQL_DATABASE=tango
    depends_on:
     - mysql
